version: "3.8"

services:
  app1:
    build:
      context: ./app
    volumes:
      - ./app/logs:/usr/src/app/logs
    networks:
      - app_network
  app2:
    build:
      context: ./app
    volumes:
      - ./app/logs:/usr/src/app/logs
    networks:
      - app_network
  app3:
    build:
      context: ./app
    volumes:
      - ./app/logs:/usr/src/app/logs
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network: